export const townsAndCities = [
  "Adelaide (SA)",
  "Albany (WA)",
  "Ayr (QLD)",
  "Brisbane (QLD)",
  "Bundaberg (QLD)",
  "Cairns (QLD)",
  "Charters Towers (QLD)",
  "Dalby (QLD)",
  "Gladstone (QLD)",
  "Gold Coast (QLD)",
  "Gympie (QLD)",
  "Hervey Bay (QLD)",
  "Innisfail (QLD)",
  "Mackay (QLD)",
  "Maryborough (QLD)",
  "Melbourne (VIC)",
  "Moranbah (QLD)",
  "Mount Isa (QLD)",
  "Perth (WA)",
  "Rockhampton (QLD)",
  "Sunshine Coast (QLD)",
  "Sydney (NSW)",
  "Toowoomba (QLD)",
  "Townsville (QLD)",
  "Warwick (QLD)",
  // Add as many cities as required...
];
